### ISSUE TITLE
BORDA research paper

### ISSUE THREAD

**Issue by Sabir97** [Valdecy/pyDecision#10]
1- I can't access the research paper associated with BORDA on the pyDecision website.
2- Is this method the same as BORDA Count ?
3- Why are the alternatives with lowest value ranked first ?
4- If this is the same as BORDA Count, BORDA Count doesn't support Multi criteria, it's a voting procedure.

**Comment by Valdecy** [comment]
1- Try this link : https://drive.google.com/file/d/1rDwTDt8gqoG4dcG20a8ETpG9VupWMMYP/view?usp=sharing
2-No. The method was based on the work of a Brazilian researcher (text in Portuguese-br): http://www.producao.uff.br/images/rpep/2014/RPEP_-_B1.pdf
3-Consult the article in 2
4-Consult the article in 2
