### ISSUE TITLE
PROMETHEE Distance and Preference Degree Matrices Dimensions

### ISSUE THREAD

**Issue by Sabir97** [Valdecy/pyDecision#11]
In the promethee methods, i think the distance_array and pd_array have incorrect dimensions.
Distance matrix x axis has: n(n-1) elements (n being number of alternatives) and  y axis has: m criteria.
Because each alternative is compared to other alternatives except itself, and those comparisons are done for each criterion.
Meaning the matrix dimensions for distance and preference are: n(n-1) x m
I found this after i was using memory_profiler to calculate the space complexity of different methods, and found that suprinsigly PROMETHEE 2 had took less space than MAUT, SAW and TOPSIS. Which is shouldn't happen.

**Comment by Valdecy** [comment]
That's what I did, in a different way. I just calculate for an nxn matrix (ignoring the diagonal to compare an alternative with itself) for a criterion, then for the next criterion I do the same thing but accumulate the last value.
