### ISSUE TITLE
AHP Type 2

### ISSUE THREAD

**Issue by mzarchi** [Valdecy/pyDecision#12]
According to the published codes, this library is not able to be used in AHP Type 2, right? And do you have a solution for this issue?

**Comment by Valdecy** [comment]
Hello there! Do you have an article that describes this algorithm? I can try to code and include it.

**Comment by mzarchi** [comment]
Yes, of course, this link is for you to study and develop the code:

* [Multilevel AHP approach with interval type-2 fuzzy sets to portfolio selection problem](https://content.iospress.com/articles/journal-of-intelligent-and-fuzzy-systems/ifs200512)

**Comment by Valdecy** [comment]
Hello, there! I regret to inform you that the implementation of this method was unsuccessful. Despite considerable effort, the calculated results didn't align as expected. My sincere apologies for the inconvenience.
