### ISSUE TITLE
TODIM

### ISSUE THREAD

**Issue by jlduu** [Valdecy/pyDecision#13]
Hello, nice Python package for MCDA, do you have a solution for TODIM?

**Comment by Valdecy** [comment]
Hello! Do you have an article that describes this algorithm? I can try to code it.

**Comment by jlduu** [comment]
> Hello! Do you have an article that describes this algorithm? I can try to code it.

Sure, please check the file:
[TODIM.pdf](https://github.com/Valdecy/pyDecision/files/11279267/TODIM.pdf)

**Comment by Valdecy** [comment]
Hello there! I've successfully implemented the TODIM method. On an interesting note, one of the original authors of the TODIM method, Luís Alberto Duncan Rangel, was my professor in the past. This makes the accomplishment all the more special to me.

**Comment by jlduu** [comment]
many many thanks！

**Comment by jlduu** [comment]
> Hello there! I've successfully implemented the TODIM method. On an interesting note, one of the original authors of the TODIM method, Luís Alberto Duncan Rangel, was my professor in the past. This makes the accomplishment all the more special to me.

Wow, what a wonderful fate, thank you very much.
