### ISSUE TITLE
Decision analysis - Decision Tree

### ISSUE THREAD

**Issue by vnijs** [Valdecy/pyDecision#14]
I created an app in R using `shiny` and  the `data.tree` to help students with decision analysis / decision trees. Does your pyDecision package offer similar functionality to what is linked below? If not, do you perhaps know of python packages that do?

Data.Tree example:
https://cran.r-project.org/web/packages/data.tree/vignettes/applications.html#jenny-lind-decision-tree-plotting

Decision Analysis tool in Radiant:
https://radiant-rstats.github.io/docs/model/dtree.html

**Comment by Valdecy** [comment]
Greetings! Currently, my library does not support these functionalities. However, I would highly recommend exploring the scikit-learn library in Python. It offers robust machine-learning algorithms that you might find helpful in your needs. 

However, I have some codes you might be interested.

CART: https://github.com/Valdecy/CART
ID3: https://github.com/Valdecy/Iterative-Dichotomiser-3
C4.5: https://github.com/Valdecy/C4.5
Random Forest: https://github.com/Valdecy/Random-Forest

**Comment by vnijs** [comment]
Thanks for your reply @Valdecy. However, I'm not looking for ML. tools. sklearn is indeed great for estimating decision trees on data. Decision Analysis, confusingly, also uses the term Decision Tree to lay out the probabilities and payoffs for different decisions scenarios. These "trees" are used to determine what the optimal decision path would be. See the screenshots below where we, first, describe the payoffs and probabilities and then construct and calculate the expected values for the different scenarios. Have you seen anything for decision analysis in python?

![image](https://github.com/Valdecy/pyDecision/assets/2998956/0df3dd1b-95c3-4996-8f54-4c952295789d)

![image](https://github.com/Valdecy/pyDecision/assets/2998956/a0d4409a-844b-4389-8798-874e04e8f59e)

**Comment by Valdecy** [comment]
Ah, I see. Unfortunately, I'm not aware of any Python library that can accomplish that right off the bat.
