### ISSUE TITLE
Answers not matching with AHP

### ISSUE THREAD

**Issue by traderbhai** [Valdecy/pyDecision#15]
I was checking the answers against the given Paper (pdf) and realized that answers are not matching for most of the algorithms, for example for AHP following should be the answers:

![image](https://github.com/Valdecy/pyDecision/assets/45916388/31679215-1249-45ce-8837-7ac8cc064fd8)

But i am getting following (although keeping input exactly same as given in the paper):
w(g1):  0.175
w(g2):  0.063
w(g3):  0.149
w(g4):  0.019
w(g5):  0.036
w(g6):  0.042
w(g7):  0.167
w(g8):  0.35

**Comment by Valdecy** [comment]
Hello!

I will investigate the issue, but it likely stems from how the eigenvalues are calculated. Minor weight discrepancies can sometimes occur, but they typically don't pose a significant problem. Nonetheless, I'll re-run the calculations as soon as possible to ensure everything is in order.

**Comment by traderbhai** [comment]
I have tried with other available apps online and surprisingly the answer of those apps matches 100% with the paper, so i am sure its an issue with your code.

**Comment by Valdecy** [comment]
As suspected, the divergence was related to the way we were calculating the eigenvalues. To address this, I have implemented an option wd = 'me', allowing the calculation to be aligned with the paper's method. This should rectify the discrepancies you found.

However, I would like to note that I still prefer the geometric mean approach (wd = 'g'), despite its potential for minor differences. It often provides a more mathematically coherent representation for certain problems.
