### ISSUE TITLE
Methods use different python types for weight parameter

### ISSUE THREAD

**Issue by ksahbaz** [Valdecy/pyDecision#16]
Some methods use python list for weight and others use numpy array.

E.g., TOPSIS uses `weights = np.array([ [0.25, 0.25, 0.25, 0.25] ])`, CoCoSo uses `weight = [0.25, 0.25, 0.25, 0.25]`. When I try to use different methods on the same data, I need to squezee numpy arrays or convert the list to numpy array.

It would be reasonable if all methods use the same type (either python list or numpy array).

Thank you for this library that contains many methods together.

**Comment by Valdecy** [comment]
I will address this issue in the next version of the library, aiming for a more uniform interface that will make it easier to switch between different methods without the need for data type conversions.

**Comment by Valdecy** [comment]
I'm pleased to inform you that the issue has been addressed in the latest version of the library, 4.2.7. From this version onward, all methods will accept weights as Python lists, making it easier to work with different methods on the same dataset.
