### ISSUE TITLE
FBWM

### ISSUE THREAD

**Issue by fight12** [Valdecy/pyDecision#17]
Hello, nice Python package for MCDA, do you have a solution for FBWM? please check the file,thank you very much.
[Fuzzy best-worst multi-criteria decision-making method and its applications.pdf](https://github.com/Valdecy/pyDecision/files/13292116/Fuzzy.best-worst.multi-criteria.decision-making.method.and.its.applications.pdf)

**Comment by Valdecy** [comment]
Hi! I will try to implement it

**Comment by fight12** [comment]
Thank you 🙂

**Comment by Valdecy** [comment]
I recommend exploring pyDecision version 4.3.5, which includes the implementation of the FBWM (Fuzzy Best-Worst Method). In this version, I have utilized the scipy library for optimization. While the scipy solver is competent, it might not always yield the most optimal solutions, and the results could be slightly different from those presented in the paper.

I have introduced an "eps_penalty" control parameter to enhance the model's performance. This parameter can be adjusted from 0 to infinity, providing flexibility in the model's operation. Be cautious with setting a very high value for "eps_penalty," as it may lead to the model violating some constraints.

For a practical demonstration, I encourage you to check out an example based on the second case study in the article. You can access it here: [Example on Google Colab](https://colab.research.google.com/drive/1hBTXyOLpBoC7oE-hsolPH2O0ekzp4VU0?usp=sharing).

**Comment by fight12** [comment]
thank you very much.
