### ISSUE TITLE
PROMETHEE criterion type is necessary

### ISSUE THREAD

**Issue by Sabir97** [Valdecy/pyDecision#19]
In PROMETHEE specifying the criterion type is necessary and it can't be replaced by using negative values or their inverse. Because in the research paper of PROMETHEE  methods 2016, the author of PROMETHEE said that in case the criterion is a minimization criterion then we should either reverse the preference function or add a minus sign to the evaluative difference between the two alternatives. Which is different from using the negatives of two evaluations.
![image](https://github.com/Valdecy/pyDecision/assets/52837091/83b11f11-6eb7-4b8b-a676-74458aaf86bc)

**Comment by Valdecy** [comment]
Hello Sabir,
In mathematical terms, converting minimization criteria to negative values effectively mirrors the operation of appending a minus sign to the difference between two alternatives. Both ways of adjustment yield an identical Net result.
