### ISSUE TITLE
Documentation about the methods and their parameters.

### ISSUE THREAD

**Issue by GiorgosPeikos** [Valdecy/pyDecision#2]
Hello, 

thank you very much for implementing all these approaches. I would like to ask you if I can find somewhere a documentation that describes to your implementations (mainly the considered parameters). 

In particular, I would like to know what are the Q S P W F parameters that are associated with the PROMETHEE II method.

**Comment by Valdecy** [comment]
The documentation is a WIP. In the meantime, you can check the PROMETHEE  parameters here: https://www.cin.ufpe.br/~if703/aulas/promethee.pdf
