### ISSUE TITLE
Non-beneficial criterion representation 

### ISSUE THREAD

**Issue by nanizdo** [Valdecy/pyDecision#5]
Hello, 

I want to know if there's a way specify that a criterion is non-beneficial, like in some cases we want to minimize a value for example (prices, costs, distance ...)

**Comment by Valdecy** [comment]
Hi!

Yes there is methods like CRITIC that non-beneficial criterion can be represented in the criterion ty parameter as 'min'. For example: criterion_type = ['min', 'max', 'max', 'max']. The first criterion is non-beneficial. However, in other MCDA methods, you should just invert the criterion value to obtain the minimization requirement. For example x should be 1/x.
