### ISSUE TITLE
ahp method not working on 12 criteria

### ISSUE THREAD

**Issue by Sabir97** [Valdecy/pyDecision#6]
When i apply AHP method on my 12 criteria dataset example i get this error:
![image](https://user-images.githubusercontent.com/52837091/213673419-b4222dc1-cce7-4de4-b765-0481ae3b593d.png)

**Comment by Valdecy** [comment]
Try to use the last version 2.8.4

**Comment by Sabir97** [comment]
Now it's working, Thank you 🙂.
